### ISSUE TITLE
support for OpenPGP?

### ISSUE THREAD

**Issue by nimbius** [tillitis/tillitis-key1#202]
howdy! 

not really an issue, just a humble feature request.  would it be possible to get an OpenPGP app on this card?  the hardware looks excellent.  

also sort of disappointed the threat actor theme song for APT/state sponsored wasnt more American.  Crypto AG was literally a CIA sockpuppet for decades.  Surely Wikileaks makes us a good contender for the APT theme song? 

https://github.com/tillitis/tillitis-key1/blob/main/doc/threat_model/threat_model.md

**Comment by mchack-work** [comment]
OpenPGP is on our radar, obviously, but not currently a priority.

We've been thinking about doing what we did with SSH, that is create our
own GnuPG compatible agent, instead of trying to patch gpg-agent to talk
to a TKey device app. It would probably be a lot simpler to us, at
least, although not necessarily the best for users. What do you think?

We just enabled Github Discussions for these types of feature requests
and discussions. See:

https://github.com/orgs/tillitis/discussions
